name: Login Script

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # 每天UTC时间00:00执行一次，可以根据需求调整

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run Puppeteer script
      env:
        ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
      run: node login.js
